Added favicon and website file input restrictions
padaiyal/sanitizer pull request #36
Opened 2024-08-03 23:00 UTC by the-c0d3br34k3r

## Description
Closes #35.

Added:
 - Favicon
 - Checks for website input files:
    - Maximum size
    - Number of input files

## Author's Checklist
- [ ] **These changes don't break existing dependants.** If they do, and you suggest to proceed, 
please explain why.

## Reviewer's Checklist
- [ ] **All classes have documentation comments.** - NA
- [ ] **All methods have documentation comments.** - NA
- [ ] **No parameters are hardcoded.** Should be loaded as properties instead. If there needs to be hardcoded properties, explain why.
- [ ] **All information to be logged/displayed to the user are internationalized.** If not, explain why. - Will be addressed in #21.
- [ ] **README.md has been updated if needed.**
- [ ] **pom.xml version is set to the latest date** If not, explain why. - NA

## Assignee's Checklist
- [ ] **All GitHub action checks have passed.**
- [ ] **All reviewers have approved.**
- [ ] **Relevant documentation has been updated if needed.**
- [ ] **pom.xml version is set to the latest date** If not, explain why.

2024-08-10 03:11 UTC, the-c0d3br34k3r commented on script/lib/bootstrap.bundle.js
Same version of bootstrap, just switched to using the whole bundle instead on the min bundle for certain additional functionality such as badges etc.

2024-08-16 03:12 UTC, silvs110 requested changes
When uploading an invalid har (aka one without any changes), it's not displayed in the unchanged files section. Also, it'll be good to disable the download button if the value of downloaded files is 0.
![image](https://github.com/user-attachments/assets/39aa9f55-d175-4e95-bf06-c105b121dda1)

2024-08-16 03:19 UTC, silvs110 commented
Another thing to add.  The page gets stuck loading when uploading two files with the same name

2024-08-16 06:03 UTC, the-c0d3br34k3r commented on README.md
> + - Each file cannot exceed 50 MB.
Each file cannot exceed 50 MB. At the moment, a max of 10 files can be sanitized at a time.

2024-08-16 06:04 UTC, the-c0d3br34k3r commented
> Another thing to add. The page gets stuck loading when uploading two files with the same name

How are you loading 2 files with the same name? Can you give an example?

2024-08-16 06:10 UTC, the-c0d3br34k3r commented
> When uploading an invalid har (aka one without any changes), it's not displayed in the unchanged files section. Also, it'll be good to disable the download button if the value of downloaded files is 0. ![image](https://private-user-images.githubusercontent.com/24996365/358456247-39aa9f55-d175-4e95-bf06-c105b121dda1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3ODg3NTQsIm5iZiI6MTcyMzc4ODQ1NCwicGF0aCI6Ii8yNDk5NjM2NS8zNTg0NTYyNDctMzlhYTlmNTUtZDE3NS00ZTk1LWJmMDYtYzEwNWIxMjFkZGExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDA2MDczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0NTc1MGM4OTc1MmZlNTI3ZTJmNDBlN2Y1OTU3NjkzZDBlYWU5Y2ZiZjg0MmVjMGZiODNiOGYyZmJjYzYwOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CpUbODD9HuCpraI2bL2Yvg5G0NdqINHz0EBXPf8idHQ)

Do you have the latest changes in this branch? I'm able to see it in the unchanged files section and the download button is disabled.
<img width="1781" alt="Screenshot 2024-08-15 at 11 09 40 PM" src="https://github.com/user-attachments/assets/f00fc50e-cbe3-4009-a8c9-76d215b03ee1">

2024-08-16 19:22 UTC, silvs110 commented
> > Another thing to add. The page gets stuck loading when uploading two files with the same name
> 
> How are you loading 2 files with the same name? Can you give an example?
Have file.har in directory A and another file.har (different content) in directory B

2024-08-16 19:25 UTC, silvs110 commented
> > When uploading an invalid har (aka one without any changes), it's not displayed in the unchanged files section. Also, it'll be good to disable the download button if the value of downloaded files is 0. ![image](https://private-user-images.githubusercontent.com/24996365/358456247-39aa9f55-d175-4e95-bf06-c105b121dda1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3ODg3NTQsIm5iZiI6MTcyMzc4ODQ1NCwicGF0aCI6Ii8yNDk5NjM2NS8zNTg0NTYyNDctMzlhYTlmNTUtZDE3NS00ZTk1LWJmMDYtYzEwNWIxMjFkZGExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDA2MDczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0NTc1MGM4OTc1MmZlNTI3ZTJmNDBlN2Y1OTU3NjkzZDBlYWU5Y2ZiZjg0MmVjMGZiODNiOGYyZmJjYzYwOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CpUbODD9HuCpraI2bL2Yvg5G0NdqINHz0EBXPf8idHQ)
> 
> Do you have the latest changes in this branch? I'm able to see it in the unchanged files section and the download button is disabled. <img alt="Screenshot 2024-08-15 at 11 09 40 PM" width="1781" src="https://private-user-images.githubusercontent.com/17999584/358486605-f00fc50e-cbe3-4009-a8c9-76d215b03ee1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MzY1MDUsIm5iZiI6MTcyMzgzNjIwNSwicGF0aCI6Ii8xNzk5OTU4NC8zNTg0ODY2MDUtZjAwZmM1MGUtY2JlMy00MDA5LWE4YzktNzZkMjE1YjAzZWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDE5MjMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1MDUxYjFkOGQ4N2Y1ODY5NTQ4YmVlN2FjNGI0Yzg3ZDhmNTI1MzAyZTNjN2E2MzdjZTE4ZjFmNzZlYTE0MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EQe2BmmCjmEtZmD09OjAPEB22jr3C-MrB8h9iMpdFLE">

My bad. The rebased version disables the downloaded button if there's no files to download

2024-08-19 20:16 UTC, the-c0d3br34k3r commented
@silvs110, With the latest changes, when an invalid HAR file is selected, it shows an alert and reverts to the initial layout.
<img width="1781" alt="Screenshot 2024-08-19 at 1 16 36 PM" src="https://github.com/user-attachments/assets/c9e641b1-fa67-4745-9a6b-e634fa2a937f">

2024-08-22 02:11 UTC, silvs110 approved these changes

2024-08-22 02:11 UTC, merged